name: ujian_flutter
description: A Flutter application with GetX and other features.

publish_to: "none" # This determines whether the package is publicly visible or private.

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # # Add assets here if needed.
  # assets:
  #   - assets/images/
  #   - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
